version: '3.8'
services:
  mi-sitio-saint:
    build: .  # Esto le dice que use el Dockerfile
    image: saint-site:latest
    networks:
      - saint_sainthn_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.saint-router.rule=Host(`saint.sainthn.com`)"
        - "traefik.http.services.saint-service.loadbalancer.server.port=80"
    restart_policy:
      condition: on-failure

networks:
  saint_sainthn_default:
    external: true
