version: '3.8'

services:
  mi-sitio-saint:
    image: nginx:alpine
    ports:
      - "8080:80" # El puerto 8080 será por donde accedas externamente
    volumes:
      - ./:/usr/share/nginx/html # Copia los archivos de tu repo al servidor web
    restart: always
